spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.56.20:9300
      repositories:
        enabled: true
  rabbitmq:
    host: 172.30.0.111
    username: rabbitci
    password: RLXL7RTFK7NJ9MJ
server:
  port: 8082

analyze:
  cardtransaction:
    queue: analyze.channel.cardtransaction
    parentid: 0
  transaction:
    queue: analyze.channel.transaction
    parentid: 0
