spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.56.20:9300
      repositories:
        enabled: true
  rabbitmq:
    host: 192.168.56.20
    port: 5672
    username: rabbitmq
    password: rabbitmq
server:
  port: 8082

analyze:
  cardtransaction:
    queue: analyze.channel.cardtransaction
    parentid: 0
  transaction:
    queue: analyze.channel.transaction
    parentid: 0
